---
- name: yum install
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - httpd
  notify: restart apache

- name: ログディレクトリのパーミッション変更
  file:
    path: /var/log/httpd
    mode: 0755
    recurse: no
